from gqlapi.resolvers.t_trade import TTradeResolver
from gqlapi.types.t_trade_types import TTradeTimeExitMode


def test_global_monitor_projects_time_exit_enum():
  monitor = TTradeResolver._global_monitor_type(
    {
      "config_id": None,
      "strategy_run_id": None,
      "universe_revision": 0,
      "account_id": "account-1",
      "enabled": False,
      "mode": "paper",
      "auto_exit_acknowledged": False,
      "ignored_stock_codes": [],
      "config_version": 0,
      "target_trade_amount": 10_000.0,
      "max_trade_amount": 12_000.0,
      "max_concurrent_batches": 3,
      "max_total_t_exposure_pct": 0.1,
      "signal_lookback_seconds": 300,
      "stabilization_seconds": 15,
      "pullback_threshold_pct": 0.8,
      "rebound_threshold_pct": 0.2,
      "max_spread_ticks": 3,
      "approval_ttl_seconds": 30,
      "max_price_deviation_pct": 0.3,
      "target_profit_pct": 2.0,
      "base_floor_pct": 0.5,
      "initial_gap_pct": 1.5,
      "trailing_gap_slope": 0.25,
      "max_gap_pct": 3.0,
      "hard_stop_enabled": False,
      "hard_stop_pct": -0.8,
      "time_exit_mode": "UNLIMITED",
      "time_exit_time": "14:50",
      "max_holding_trading_days": 5,
      "cooldown_seconds": 300,
      "holding_count": 0,
      "eligible_count": 0,
      "ignored_count": 0,
      "monitored_count": 0,
      "pending_signal_count": 0,
      "active_batch_count": 0,
      "draining_count": 0,
      "holdings": [],
      "sessions": [],
      "position_snapshot_source": None,
      "position_snapshot_sequence": "0",
      "position_snapshot_reported_at": None,
      "position_snapshot_received_at": None,
      "position_snapshot_complete": False,
      "position_snapshot_error": None,
      "last_reconciled_at": None,
      "last_error": None,
      "created_at": None,
      "updated_at": None,
    }
  )

  assert monitor.time_exit_mode is TTradeTimeExitMode.UNLIMITED
