"""Runtime provenance for source trees published by the Trainer unpacker."""

import hashlib
import json
import os
import re
import stat
from pathlib import Path, PurePosixPath

MARKER = ".trainer-source.json"


def packaged_source_state(root: Path):
  marker = root / MARKER
  if not os.path.lexists(marker):
    return None
  try:
    if marker.is_symlink() or marker.stat().st_size > 8 * 1024 * 1024:
      raise ValueError
    with marker.open("rb") as stream:
      raw = stream.read(8 * 1024 * 1024 + 1)
    if len(raw) > 8 * 1024 * 1024:
      raise ValueError
    manifest = json.loads(raw)
    if (
      type(manifest["schema_version"]) is not int
      or manifest["schema_version"] != 1
      or manifest["kind"] != "trainer-code"
      or not re.fullmatch(r"[0-9a-f]{40}|[0-9a-f]{64}", manifest["git_commit"])
      or not isinstance(manifest["files"], list)
      or not manifest["files"]
    ):
      raise ValueError
    expected, folded, changes = set(), set(), []
    for item in manifest["files"]:
      name = item["path"]
      relative = PurePosixPath(name)
      if (
        relative.is_absolute()
        or str(relative) != name
        or any(part in {".", ".."} for part in relative.parts)
        or not relative.parts
        or "\\" in name
        or ":" in name
        or name == MARKER
        or name.casefold() in folded
        or type(item["size"]) is not int
        or item["size"] < 0
        or not re.fullmatch(r"[0-9a-f]{64}", item["sha256"])
      ):
        raise ValueError
      expected.add(name)
      folded.add(name.casefold())
      path = root / name
      linked = any(
        p.is_symlink()
        or (p.exists() and getattr(p.lstat(), "st_file_attributes", 0) & 0x400)
        for p in (
          path,
          *[root.joinpath(*relative.parts[:i]) for i in range(1, len(relative.parts))],
        )
      )
      if linked or not path.is_file() or path.stat().st_size != item["size"]:
        changes.append(name)
        continue
      with path.open("rb") as stream:
        if hashlib.file_digest(stream, "sha256").hexdigest() != item["sha256"]:
          changes.append(name)

    # Unexpected source/native modules must never be reported as a clean image.
    # Only interpreter-generated bytecode caches are excluded, like Git ignores.
    def unavailable(error):
      raise error

    for directory, folders, files in os.walk(
      root, followlinks=False, onerror=unavailable
    ):
      linked_folders = set()
      for name in (*folders, *files):
        path = Path(directory) / name
        relative = path.relative_to(root).as_posix()
        info = path.lstat()
        linked = (
          stat.S_ISLNK(info.st_mode) or getattr(info, "st_file_attributes", 0) & 0x400
        )
        if linked:
          linked_folders.add(name)
        if linked or (
          not stat.S_ISDIR(info.st_mode)
          and relative != MARKER
          and relative not in expected
        ):
          changes.append(relative)
      folders[:] = [
        name for name in folders if name != "__pycache__" and name not in linked_folders
      ]
    return {
      "commit": manifest["git_commit"],
      "dirty": bool(changes),
      "status_fingerprint": hashlib.sha256(
        json.dumps(
          sorted(set(changes)), ensure_ascii=False, separators=(",", ":")
        ).encode()
      ).hexdigest(),
      "code_manifest_sha256": hashlib.sha256(raw).hexdigest(),
    }
  except (OSError, ValueError, TypeError, KeyError, AttributeError):
    raise ValueError("TRAINER_SOURCE_EVIDENCE_INVALID") from None
