"""Common trading-domain utilities shared by strategies, brokers, and executor."""

from .bucket_ledger import (
  BucketLedger,
  BucketLedgerPatch,
  BucketLedgerSnapshot,
  BucketPositionState,
  SubstitutionPlan,
  SubstitutionStatus,
)
from .data_context import AshareDataContext, AshareDataContextProvider
from .decision_trace import DecisionTrace, DecisionTraceLogger
from .environment import (
  EnvironmentLayer,
  MarketContextSnapshot,
)
from .environment import (
  MarketContextSnapshot as EnvironmentSnapshot,
)
from .entry_plan import (
  CausalPriceObservation,
  EntryAuthorizationMode,
  EntryBaselineSnapshot,
  EntryCompletionPolicy,
  EntryDecision,
  EntryEnvironment,
  EntryEvaluationContext,
  EntryEvaluationResult,
  EntryGapCalculator,
  EntryGapResult,
  EntryPacingPolicy,
  EntryPlanStatus,
  EntryRuleSpec,
  EntryRuleType,
  EntryTargetMode,
  EntryTargetPolicy,
  ManagedEntryPlanConfig,
  ManagedEntryPlanEvaluator,
  ManagedEntryPlanState,
  PendingBuyExposure,
)
from .exit_plan import (
  EXIT_PLAN_BOOK_STATE_KEY,
  ExitDecision,
  ExitEvaluationContext,
  ExitExecutionPolicy,
  ExitPlan,
  ExitPlanBook,
  ExitPlanCommand,
  ExitPlanCommandType,
  ExitPlanEvaluator,
  ExitPlanStatus,
  ExitPlanTemplate,
  ExitPriceReference,
  ExitRuleEvaluator,
  ExitRuleMatch,
  ExitRuleSpec,
  ExitRuleType,
  ExitSizingMode,
  ExitSizingPolicy,
  ExitStrategyRegistry,
  ExitT1Policy,
  TradingCostPolicy,
  TrailingProfitPolicy,
  calculate_trailing_floor_pct,
  estimate_net_profit_pct,
)
from .first_board_policy import (
  FirstBoardEntryPolicy,
  FirstBoardExitPolicy,
  FirstBoardMarketSignalDecision,
  FirstBoardMarketSnapshot,
  build_first_board_exit_plan,
  evaluate_first_board_market_signal,
)
from .first_board_promotion import (
  FIRST_BOARD_EXIT_POLICY_VERSION,
  FIRST_BOARD_MODEL_VERSION,
  FirstBoardHighPositionType,
  FirstBoardPromotionAssessment,
  FirstBoardPromotionEvaluator,
  FirstBoardPromotionFactor,
  FirstBoardPromotionFeatures,
  FirstBoardSegment,
  first_board_segment,
)
from .instrument_master import InstrumentMaster, InstrumentMasterSnapshot
from .limit_up_board_replay import (
  LIMIT_UP_BOARD_REPLAY_SCENARIO_PROFILE,
  LIMIT_UP_BOARD_REPLAY_SCHEMA_VERSION,
  LIMIT_UP_BOARD_REPLAY_TERMINAL_STATUSES,
  STANDARD_V1_SCENARIOS,
  LimitUpBoardReplayScenarioSpec,
  get_limit_up_board_replay_scenarios,
)
from .market_rules import (
  AShareMarketRules,
  MarketDataSnapshot,
  OrderCheckResult,
  resolve_ashare_daily_limit_rate,
)
from .orchestration import PortfolioExecutionProfile, PortfolioOrchestrationLayer
from .order_sizer import OrderDraft, OrderSizer
from .position_adjustment import (
  PositionAdjustmentLayer,
  PositionAdjustmentProfile,
  PositionProfileName,
)
from .risk_checker import (
  ContextRiskLayer,
  OrderRiskDecision,
  RiskAction,
  RiskContextCaps,
  TradingRiskChecker,
)

__all__ = [
  "AShareMarketRules",
  "BucketLedger",
  "BucketLedgerPatch",
  "BucketLedgerSnapshot",
  "BucketPositionState",
  "SubstitutionPlan",
  "SubstitutionStatus",
  "AshareDataContext",
  "AshareDataContextProvider",
  "DecisionTrace",
  "DecisionTraceLogger",
  "EnvironmentLayer",
  "EnvironmentSnapshot",
  "CausalPriceObservation",
  "EntryAuthorizationMode",
  "EntryBaselineSnapshot",
  "EntryCompletionPolicy",
  "EntryDecision",
  "EntryEnvironment",
  "EntryEvaluationContext",
  "EntryEvaluationResult",
  "EntryGapCalculator",
  "EntryGapResult",
  "EntryPacingPolicy",
  "EntryPlanStatus",
  "EntryRuleSpec",
  "EntryRuleType",
  "EntryTargetMode",
  "EntryTargetPolicy",
  "ManagedEntryPlanConfig",
  "ManagedEntryPlanEvaluator",
  "ManagedEntryPlanState",
  "PendingBuyExposure",
  "EXIT_PLAN_BOOK_STATE_KEY",
  "ExitDecision",
  "ExitEvaluationContext",
  "ExitExecutionPolicy",
  "ExitPlan",
  "ExitPlanBook",
  "ExitPlanCommand",
  "ExitPlanCommandType",
  "ExitPlanEvaluator",
  "ExitPlanStatus",
  "ExitPlanTemplate",
  "ExitPriceReference",
  "ExitRuleEvaluator",
  "ExitRuleMatch",
  "ExitRuleSpec",
  "ExitRuleType",
  "ExitSizingMode",
  "ExitSizingPolicy",
  "ExitStrategyRegistry",
  "ExitT1Policy",
  "FIRST_BOARD_EXIT_POLICY_VERSION",
  "FIRST_BOARD_MODEL_VERSION",
  "LIMIT_UP_BOARD_REPLAY_SCHEMA_VERSION",
  "LIMIT_UP_BOARD_REPLAY_SCENARIO_PROFILE",
  "LIMIT_UP_BOARD_REPLAY_TERMINAL_STATUSES",
  "STANDARD_V1_SCENARIOS",
  "LimitUpBoardReplayScenarioSpec",
  "FirstBoardHighPositionType",
  "FirstBoardPromotionAssessment",
  "FirstBoardPromotionEvaluator",
  "FirstBoardPromotionFactor",
  "FirstBoardPromotionFeatures",
  "FirstBoardSegment",
  "FirstBoardEntryPolicy",
  "FirstBoardExitPolicy",
  "FirstBoardMarketSignalDecision",
  "FirstBoardMarketSnapshot",
  "InstrumentMaster",
  "InstrumentMasterSnapshot",
  "MarketContextSnapshot",
  "MarketDataSnapshot",
  "OrderCheckResult",
  "resolve_ashare_daily_limit_rate",
  "OrderDraft",
  "OrderSizer",
  "PositionAdjustmentLayer",
  "PositionAdjustmentProfile",
  "PositionProfileName",
  "PortfolioExecutionProfile",
  "PortfolioOrchestrationLayer",
  "OrderRiskDecision",
  "RiskAction",
  "RiskContextCaps",
  "ContextRiskLayer",
  "TradingRiskChecker",
  "TradingCostPolicy",
  "TrailingProfitPolicy",
  "calculate_trailing_floor_pct",
  "estimate_net_profit_pct",
  "build_first_board_exit_plan",
  "evaluate_first_board_market_signal",
  "first_board_segment",
  "get_limit_up_board_replay_scenarios",
]
