query Dashboard_MarketIndexSnapshots {
  shanghaiTick: ticks(stockCode: "000001.SH", limit: 1, order: "desc") {
    stockCode
    time
    lastPrice
    open
    high
    low
    preClose
    volume
  }
  shenzhenTick: ticks(stockCode: "399001.SZ", limit: 1, order: "desc") {
    stockCode
    time
    lastPrice
    open
    high
    low
    preClose
    volume
  }
  chinextTick: ticks(stockCode: "399006.SZ", limit: 1, order: "desc") {
    stockCode
    time
    lastPrice
    open
    high
    low
    preClose
    volume
  }
  kechuangCompositeTick: ticks(stockCode: "000680.SH", limit: 1, order: "desc") {
    stockCode
    time
    lastPrice
    open
    high
    low
    preClose
    volume
  }
  kechuang50Tick: ticks(stockCode: "000688.SH", limit: 1, order: "desc") {
    stockCode
    time
    lastPrice
    open
    high
    low
    preClose
    volume
  }
  csiA500Tick: ticks(stockCode: "000510.SH", limit: 1, order: "desc") {
    stockCode
    time
    lastPrice
    open
    high
    low
    preClose
    volume
  }
  csi300Tick: ticks(stockCode: "000300.SH", limit: 1, order: "desc") {
    stockCode
    time
    lastPrice
    open
    high
    low
    preClose
    volume
  }
  csi1000Tick: ticks(stockCode: "000852.SH", limit: 1, order: "desc") {
    stockCode
    time
    lastPrice
    open
    high
    low
    preClose
    volume
  }
  shanghai50Tick: ticks(stockCode: "000016.SH", limit: 1, order: "desc") {
    stockCode
    time
    lastPrice
    open
    high
    low
    preClose
    volume
  }
  shenzhen100Tick: ticks(stockCode: "399330.SZ", limit: 1, order: "desc") {
    stockCode
    time
    lastPrice
    open
    high
    low
    preClose
    volume
  }
  csi500Tick: ticks(stockCode: "000905.SH", limit: 1, order: "desc") {
    stockCode
    time
    lastPrice
    open
    high
    low
    preClose
    volume
  }
  chinext50Tick: ticks(stockCode: "399673.SZ", limit: 1, order: "desc") {
    stockCode
    time
    lastPrice
    open
    high
    low
    preClose
    volume
  }
  kechuang100Tick: ticks(stockCode: "000698.SH", limit: 1, order: "desc") {
    stockCode
    time
    lastPrice
    open
    high
    low
    preClose
    volume
  }
  shanghaiIndex: klines(stockCode: "000001.SH", period: DAY_1, limit: 1, order: "desc") {
    stockCode
    time
    open
    high
    low
    close
    preClose
    volume
  }
  shenzhenComponent: klines(stockCode: "399001.SZ", period: DAY_1, limit: 1, order: "desc") {
    stockCode
    time
    open
    high
    low
    close
    preClose
    volume
  }
  chinextIndex: klines(stockCode: "399006.SZ", period: DAY_1, limit: 1, order: "desc") {
    stockCode
    time
    open
    high
    low
    close
    preClose
    volume
  }
  kechuangComposite: klines(stockCode: "000680.SH", period: DAY_1, limit: 1, order: "desc") {
    stockCode
    time
    open
    high
    low
    close
    preClose
    volume
  }
  kechuang50: klines(stockCode: "000688.SH", period: DAY_1, limit: 1, order: "desc") {
    stockCode
    time
    open
    high
    low
    close
    preClose
    volume
  }
  csiA500: klines(stockCode: "000510.SH", period: DAY_1, limit: 1, order: "desc") {
    stockCode
    time
    open
    high
    low
    close
    preClose
    volume
  }
  csi300: klines(stockCode: "000300.SH", period: DAY_1, limit: 1, order: "desc") {
    stockCode
    time
    open
    high
    low
    close
    preClose
    volume
  }
  csi1000: klines(stockCode: "000852.SH", period: DAY_1, limit: 1, order: "desc") {
    stockCode
    time
    open
    high
    low
    close
    preClose
    volume
  }
  shanghai50: klines(stockCode: "000016.SH", period: DAY_1, limit: 1, order: "desc") {
    stockCode
    time
    open
    high
    low
    close
    preClose
    volume
  }
  shenzhen100: klines(stockCode: "399330.SZ", period: DAY_1, limit: 1, order: "desc") {
    stockCode
    time
    open
    high
    low
    close
    preClose
    volume
  }
  csi500: klines(stockCode: "000905.SH", period: DAY_1, limit: 1, order: "desc") {
    stockCode
    time
    open
    high
    low
    close
    preClose
    volume
  }
  chinext50: klines(stockCode: "399673.SZ", period: DAY_1, limit: 1, order: "desc") {
    stockCode
    time
    open
    high
    low
    close
    preClose
    volume
  }
  kechuang100: klines(stockCode: "000698.SH", period: DAY_1, limit: 1, order: "desc") {
    stockCode
    time
    open
    high
    low
    close
    preClose
    volume
  }
}
