apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: quantx
resources:
  - namespace.yaml
  - service-account.yaml
  - platform-config.yaml
  - api.yaml
  - market-data-service.yaml
  - engine.yaml
  - worker.yaml
  - ai-runtime.yaml
  - monitor.yaml
  - gateway.yaml
images:
  - name: quantx-server
    newName: ghcr.io/limaofeng/quantx-server
    newTag: replace-me
  - name: quantx-gateway
    newName: ghcr.io/limaofeng/quantx-gateway
    newTag: replace-me
